name = "kodi-repo"
main = "worker.js"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "kodi-repo"

[[kv_namespaces]]
binding = "AUTH_RELAY"
id = "$KV_AUTH_RELAY_ID"

[[routes]]
pattern = "kodi.zales.dev/*"
zone_name = "zales.dev"
